### ISSUE TITLE
Defaults in example_config.yml do not work well with Trust Monitor endpoint

### ISSUE THREAD

**Issue by MarkTripod-Duo** [duosecurity/duo_log_sync#34]
The default 180 day maximum in the example_config.yml is not handled properly by the API and results in a 400 error. Also, the default timeout value of 120 can result in a 429 error due to how the duo_client automatically handles silent retries for API calls. Inclusion of the "activity" endpoint will also cause the duo_log_sync app to fail when that endpoint is not available.

```yaml
version: "1.0.0"

dls_settings:
  log_filepath: "/tmp/duologsync.log"
  log_format: "JSON"

  api:
    offset: 179
    timeout: 150

  checkpointing:
    enabled: True
    directory: "/tmp"

servers:
  - id: "test"
    hostname: "127.0.0.1"
    port: 8888
    protocol: "TCP"

account:
  ikey: "admin-api-ikey"
  skey: "admin-api-skey"
  hostname: "host.name.com"

  endpoint_server_mappings:
    - endpoints:
        ["adminaction", "auth", "telephony", "trustmonitor"]
      server: "test"
  is_msp: False
```
