### ISSUE TITLE
Mintime errors

### ISSUE THREAD

**Issue by Voilett-Roze** [duosecurity/duo_log_sync#36]
Hi Im receiving errors with the trustmonitor, auth and activity logs.

2023-04-22 20:59:55 WARNING  DuoLogSync: Shutting down due to [trustmonitor producer: [Received 400 Invalid request parameters (mintime must be within the past 180 days)]]
2023-04-22 20:59:55 WARNING  DuoLogSync: Shutting down due to [activity producer: [Received 400 Invalid request parameters ('mintime' must be a timestamp in milliseconds)]]
2023-04-22 20:59:54 WARNING  DuoLogSync: Shutting down due to [auth producer: [Received 400 Invalid request parameters ('mintime' must be a timestamp in milliseconds)]]

Am receiving queued logs admin action and telephony. Was receiving logs successfully until i updated the the code to the recently updated ones. 
2023-04-22 20:59:55 ERROR    DuoLogSync: check that the duoclient ikey and skey in the config file are correct

Have tried converting past 180 days to milliseconds to set mintime, with no success.

**Comment by giveen** [comment]
Same here

**Comment by MarkTripod-Duo** [comment]
I have seen instances in the past where certain conditions can cause the translation of an `offset` value of 180 in the config.yml to exceed the maximum allowed by the API. Do you still see the errors if you set the offset to 179?

**Comment by giveen** [comment]
> I have seen instances in the past where certain conditions can cause the translation of an `offset` value of 180 in the config.yml to exceed the maximum allowed by the API. Do you still see the errors if you set the offset to 179?

My offset is set to 1, because i only pull 1 day of logs in at a time.

It looks to be a change in the API

https://github.com/mbegan/Duo-PSModule/issues/46

**Comment by MarkTripod-Duo** [comment]
Nothing has changed in the API. The version 2 log endpoints require timestamps in milliseconds. This is a departure from the original version 1 log endpoints expecting a timestamp in seconds. The Duo Log Sync program takes this into account based upon the `- endpoints: []` configuration in the YAML file.

**Comment by giveen** [comment]
> Nothing has changed in the API. The version 2 log endpoints require timestamps in milliseconds. This is a departure from the original version 1 log endpoints expecting a timestamp in seconds. The Duo Log Sync program takes this into account based upon the `- endpoints: []` configuration in the YAML file.

Please give an example on what to set, because its not working.

**Comment by MarkTripod-Duo** [comment]
```version: "1.0.0"

dls_settings:
  log_filepath: "/tmp/duologsync.log"
  log_format: "JSON"

  api:
    offset: 179
    timeout: 180

  checkpointing:
    enabled: True
    directory: "/tmp"

servers:
  - id: "test"
    hostname: "127.0.0.1"
    port: 514
    protocol: "TCP"

account:
  ikey: "admin-api-ikey"
  skey: "admin-api-skey"
  hostname: "host.name.com"

  endpoint_server_mappings:
    - endpoints:
        ["auth", "telephony", "trustmonitor"]
      server: "test"
  is_msp: False```

The configuration above (after having the `account` information updated) would collect the authentication logs. telephony logs and Trust Monitor logs from the Duo Admin API. On first run it would look back 179 days and then create a checkpoint file in /tmp for tracking how far back to look for each successive polling of the API log endpoints.

**Comment by giveen** [comment]
Literally what I have, still same error.
its interesting how you say "there was no change", but at the same time you say "well logs require a different timestamp now", thats a change.

```
version: '1.0.0'

dls_settings:
  log_filepath: '/var/log/duologsync/duologsync.log'
  log_format: 'JSON'

  api:
    offset: 1
    timeout: 120
    
servers:
  - id: 'Graylog'
    hostname: xx.xx.xx.xx
    port: 1514
    protocol: 'UDP'

account:
  ikey: 'xxxxxxxxxxxxxxxxx'
  skey: 'xxxxxxxxxxxxxxxxxxx'
  hostname: 'xxxxxxxxxxxxxxxx.duosecurity.com'
    
  endpoint_server_mappings:
    - endpoints: ['adminaction', 'auth', 'telephony', 'activity']
      server: 'Graylog'
  is_msp: False
```
